### ISSUE TITLE
Setup use case

### ISSUE THREAD

**Issue by seanauriti** [Emrals/HexBin#13]

**Comment by mashcode** [comment]
The HexBin vending machine is a solution designed to give secondhand items a much deserved second life. Residential high density housing units and high traffic small neighborhood businesses can benefit from a system that appeals to those that appreciate the local recirculation of lightly used items.

While outlets like Ebay, Craiglist and Freecycle provide a virtual space for some to peddle and share new and used items those platforms are not for everyone.  The investment in time, packaging and shipping, returned merchandize, the randomness of potential local buyers can be a significant barrier to many.  

So much useful stuff languishing in cluttered closets or doomed to landfills and incinerators.  What can be more thrilling than seeing a neighbor keeping warm and looking chic is your seldom used cashmere scarf.

**Comment by seanauriti** [comment]
Thanks!
